export const Users = [
  {
    id: 1,
    profilePicture: "./assets/person/1.jpg",
    username: "Lucy Barbies",
  },
  {
    id: 2,
    profilePicture: "./assets/person/2.jpg",
    username: "Cristiano Ronaldo",
  },
  {
    id: 3,
    profilePicture: "./assets/person/3.jpg",
    username: "Justin Beiber",
  },
  {
    id: 4,
    profilePicture: "./assets/person/4.jpg",
    username: "Neymar JR",
  },
  {
    id: 5,
    profilePicture: "./assets/person/5.jpg",
    username: "Charlie Puth",
  },
  {
    id: 6,
    profilePicture: "./assets/person/6.jpg",
    username: "Hanakoishi",
  },
  {
    id: 7,
    profilePicture: "./assets/person/7.jpg",
    username: "Tommy Shelby",
  },
  {
    id: 8,
    profilePicture: "./assets/person/8.jpg",
    username: "Jackie Chan",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Happy girls are the prettiest:3",
    photo: "./assets/post/1.jpg",
    date: "7 mins ago",
    userId: 1,
    like: 156,
    comment: 37,
  },
  {
    id: 2,
    desc: "Love For All <3",
    photo: "./assets/post/2.jpg",
    date: "12 mins ago",
    userId: 2,
    like: 728,
    comment: 12,
  },
  {
    id: 3,
    desc: "I love you 3000",
    photo: "./assets/post/3.jpg",
    date: "30 mins ago",
    userId: 3,
    like: 363,
    comment: 33,
  },
  {
    id: 4,
    desc: "4 Seasons miss you",
    photo: "./assets/post/4.jpg",
    date: "42 mins ago",
    userId: 4,
    like: 444,
    comment: 84,
  },
  {
    id: 5,
    desc: "Feeling Good!",
    photo: "./assets/post/5.jpg",
    date: "19 mins ago",
    userId: 5,
    like: 715,
    comment: 195,
  },
  {
    id: 6,
    desc: "Santa villa ohhhhh!",
    photo: "./assets/post/6.jpg",
    date: "6 mins ago",
    userId: 6,
    like: 164,
    comment: 32,
  },
  {
    id: 7,
    desc: "Be a man!",
    photo: "./assets/post/7.jpg",
    date: "14 mins ago",
    userId: 7,
    like: 255,
    comment: 22,
  },
  {
    id: 8,
    desc: "Young Boy 2018 :))",
    photo: "./assets/post/8.jpg",
    date: "30 mins ago",
    userId: 8,
    like: 242,
    comment: 36,
  },
];
